# Generated by Django 5.2.17 on 2026-09-18 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='founder/')),
                ('studio_image', models.ImageField(blank=True, null=True, upload_to='founder/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('cta_url', models.CharField(default='/artworks', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='İlqar Məmmədov — Rəssamlıq Platforması', max_length=200)),
                ('contact_email', models.EmailField(default='art@expertvisits.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+994 50 000 00 00', max_length=50)),
                ('address', models.CharField(blank=True, default='Bakı, Azərbaycan', max_length=250)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AboutPageTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=5)),
                ('biography_title', models.CharField(default='İlqar Məmmədov', max_length=250)),
                ('biography_text', models.TextField()),
                ('founder_story_title', models.CharField(default='Yaradıcılıq Yolu', max_length=250)),
                ('founder_story_text', models.TextField()),
                ('mission_title', models.CharField(default='Missiyamız', max_length=250)),
                ('mission_text', models.TextField(help_text='Supporting artists and creators embarking on the art path')),
                ('vision_title', models.CharField(default='Vizyonumuz', max_length=250)),
                ('vision_text', models.TextField()),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.aboutpagecontent')),
            ],
            options={
                'unique_together': {('about_page', 'language')},
            },
        ),
        migrations.CreateModel(
            name='HeroBannerTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('cta_text', models.CharField(default='Kəşf et', max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.herobanner')),
            ],
            options={
                'unique_together': {('banner', 'language')},
            },
        ),
    ]
