server {
  listen 80;
  server_name artexperts.net;
  location = /nginx-health { access_log off; return 200 'ok'; }
  location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; }
  location / {
    proxy_pass http://artexperts_frontend;
    include /etc/nginx/artexperts/proxy-headers.conf;
  }
}
server {
  listen 80;
  server_name app.artexperts.net;
  location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; }
  include /etc/nginx/artexperts/backend-locations.conf;
}
