# Generated by Django 5.2.17 on 2026-09-18 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('artist_attribution', models.CharField(blank=True, help_text='Displayed artist name', max_length=200)),
                ('moderation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_founder_piece', models.BooleanField(db_index=True, default=False, help_text='Masterpiece by Ilqar Mammadov')),
                ('creation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, default='', help_text='e.g. Oil on Canvas', max_length=150)),
                ('dimensions', models.CharField(blank=True, default='', help_text='e.g. 100 x 80 cm', max_length=100)),
                ('allow_download', models.BooleanField(default=False, help_text='Allows public visitors to download high-res detail')),
                ('is_watermarked', models.BooleanField(default=False)),
                ('original_master', models.ImageField(upload_to='private/artworks/masters/')),
                ('detail_image', models.ImageField(blank=True, upload_to='artworks/details/')),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='artworks/thumbnails/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('rights_confirmed', models.BooleanField(default=True, help_text='Uploader confirms ownership or publishing rights')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_az', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Artwork Category',
                'verbose_name_plural': 'Artwork Categories',
            },
        ),
        migrations.CreateModel(
            name='ArtworkTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
