# Generated by Django 5.2.17 on 2026-09-18 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('moderation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_founder_article', models.BooleanField(db_index=True, default=False, help_text='Written by Ilqar Mammadov')),
                ('cover_image', models.ImageField(upload_to='articles/covers/')),
                ('cover_thumbnail', models.ImageField(blank=True, upload_to='articles/thumbnails/')),
                ('reading_time_minutes', models.PositiveIntegerField(default=3)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_az', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
            },
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('excerpt', models.TextField(help_text='Short summary for listing cards')),
                ('content', models.TextField(help_text='Sanitized editorial article body')),
            ],
        ),
    ]
