# Generated by Django 5.2.17 on 2026-09-18 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cover_image', models.ImageField(upload_to='books/covers/')),
                ('digital_file', models.FileField(blank=True, null=True, upload_to='private/books/files/')),
                ('availability_mode', models.CharField(choices=[('NOT_FOR_SALE', 'Not For Sale'), ('FREE', 'Free Public Access'), ('PRIVATE_ACCESS', 'Private Granted Access'), ('FUTURE_PAID', 'Future Paid Edition')], db_index=True, default='PRIVATE_ACCESS', max_length=25)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='AZN', max_length=10)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, default='', max_length=50)),
                ('publisher', models.CharField(blank=True, default='', max_length=150)),
                ('languages', models.CharField(default='AZ', help_text='e.g. AZ, EN, RU', max_length=100)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('moderation_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_founder_book', models.BooleanField(db_index=True, default=False, help_text='Book authored/curated by Ilqar Mammadov')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookContributorLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor'), ('TRANSLATOR', 'Translator')], default='AUTHOR', max_length=25)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, max_length=5)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('short_description', models.TextField(help_text='Short description for book card')),
                ('full_description', models.TextField(help_text='Detailed book presentation')),
                ('table_of_contents', models.TextField(blank=True, default='', help_text='Book index / contents')),
            ],
        ),
    ]
