# Generated by Django 5.2.17 on 2026-09-18 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_book_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcontributor',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcontributorlink',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_links', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookcontributorlink',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_links', to='books.bookcontributor'),
        ),
        migrations.AddField(
            model_name='booktranslation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='books.book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookaccess',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='bookcontributorlink',
            unique_together={('book', 'contributor', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='booktranslation',
            unique_together={('book', 'language'), ('language', 'slug')},
        ),
    ]
