# Generated by Django 5.2.17 on 2026-09-18 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_artist', models.BooleanField(default=True, help_text='Designates whether the user can publish artwork/books.')),
                ('is_verified', models.BooleanField(default=False, help_text="Designates whether the user's email has been verified.")),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('username', models.SlugField(max_length=100, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/originals/')),
                ('avatar_thumbnail', models.ImageField(blank=True, null=True, upload_to='avatars/thumbnails/')),
                ('short_bio', models.TextField(blank=True, default='')),
                ('artist_statement', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='', max_length=300)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('specialties', models.CharField(blank=True, default='', help_text='e.g., Oil painting, Canvas, Graphic Art', max_length=250)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_founder', models.BooleanField(default=False, help_text='True for Ilqar Mammadov, the site creator.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artist Profile',
                'verbose_name_plural': 'Artist Profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('token_type', models.CharField(choices=[('REGISTER', 'Registration Verification'), ('PASSWORD_RESET', 'Password Reset')], default='REGISTER', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'code', 'is_used'], name='users_email_email_20499a_idx')],
            },
        ),
    ]
